edit_uri: ""
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      user: romsson
      repo: flatdir
      repo_url_shorthand: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
nav:
  - "index.md"
repo_name: romsson/flatdir
repo_url: https://github.com/romsson/flatdir
site_name: flatdir docs
site_url: ""
theme:
  favicon: assets/images/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.top
  font: false
  icon:
    logo: octicons/book-24
    repo: octicons/mark-github-16
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      accent: cyan
      primary: cyan
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      accent: cyan
      primary: cyan
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
use_directory_urls: false
